# Generated by Django 4.2.1 on 2023-05-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubwayLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubwayRouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('sequence', models.IntegerField()),
                ('subway_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.subwayline')),
                ('subway_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.subwaystation')),
            ],
        ),
        migrations.AddField(
            model_name='subwayline',
            name='route_stations',
            field=models.ManyToManyField(through='transit.SubwayRouteStation', to='transit.subwaystation'),
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_identifier', models.CharField(max_length=200)),
                ('estimated_arrival_time_next_stop', models.TimeField(null=True)),
                ('current_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.subwaystation')),
                ('next_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transit.subwaystation')),
                ('subway_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.subwayline')),
            ],
        ),
        migrations.CreateModel(
            name='BusRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('sequence', models.IntegerField()),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.busline')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_identifier', models.CharField(max_length=200)),
                ('estimated_arrival_time_next_stop', models.TimeField(null=True)),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.busline')),
                ('current_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.busstop')),
                ('next_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transit.busstop')),
            ],
        ),
    ]
