# Generated by Django 4.2.1 on 2023-05-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subwaystation',
            old_name='location',
            new_name='code',
        ),
    ]
