# Generated by Django 4.2.1 on 2023-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_subwaystation_line_subwaystation_name_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_id', models.IntegerField()),
                ('st_id', models.IntegerField()),
                ('st_ord', models.IntegerField()),
                ('stop_flag', models.IntegerField()),
                ('data_tm', models.IntegerField()),
                ('tm_x', models.FloatField()),
                ('tm_y', models.FloatField()),
                ('plain_no', models.CharField(max_length=100)),
                ('bus_type', models.IntegerField()),
                ('last_stn_id', models.IntegerField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('congetion', models.IntegerField()),
                ('is_full_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='busroutestop',
            name='bus_line',
        ),
        migrations.RemoveField(
            model_name='busroutestop',
            name='bus_stop',
        ),
        migrations.RemoveField(
            model_name='subway',
            name='current_station',
        ),
        migrations.RemoveField(
            model_name='subway',
            name='next_station',
        ),
        migrations.RemoveField(
            model_name='subway',
            name='subway_line',
        ),
        migrations.RemoveField(
            model_name='subwayline',
            name='route_stations',
        ),
        migrations.RemoveField(
            model_name='subwayroutestation',
            name='subway_line',
        ),
        migrations.RemoveField(
            model_name='subwayroutestation',
            name='subway_station',
        ),
        migrations.RemoveField(
            model_name='subwaystation',
            name='line',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='BusLine',
        ),
        migrations.DeleteModel(
            name='BusRouteStop',
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
        migrations.DeleteModel(
            name='Subway',
        ),
        migrations.DeleteModel(
            name='SubwayLine',
        ),
        migrations.DeleteModel(
            name='SubwayRouteStation',
        ),
        migrations.DeleteModel(
            name='SubwayStation',
        ),
    ]
