# Generated by Django 4.2.1 on 2023-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transit', '0004_busdata_remove_busroutestop_bus_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('veh_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('st_id', models.IntegerField()),
                ('st_ord', models.IntegerField()),
                ('stop_flag', models.IntegerField()),
                ('data_tm', models.IntegerField()),
                ('tm_x', models.FloatField()),
                ('tm_y', models.FloatField()),
                ('plain_no', models.CharField(max_length=100)),
                ('bus_type', models.IntegerField()),
                ('last_stn_id', models.IntegerField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('congetion', models.IntegerField()),
                ('is_full_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
