# Generated by Django 4.2.1 on 2023-06-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='congetion',
            new_name='passenger_load',
        ),
    ]
