# Generated by Django 4.2.1 on 2023-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0008_delete_bus_pushsubscription_expiration_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='p256dh',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='subscription',
            field=models.JSONField(null=True),
        ),
    ]
