# Generated by Django 4.2.1 on 2023-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0009_remove_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='subscription',
            field=models.JSONField(),
        ),
    ]
