# Generated by Django 4.2.1 on 2023-07-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0011_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transit.user'),
        ),
    ]
